version: '3.3'
services:
  # # API GATEWAY_____________
  api-gateway:
    container_name: api-gateway
    image: sandobal-api-gateway:latest
    build:
      context: api.gateway/target/docker/sandobal_gateway/
      dockerfile: Dockerfile
    networks:
      - servicenet
      - publicnet
    ports:
      - 9090:9090
    restart: always
  # # RESERVATIONS SERVICE _____________
  reservation-ms:
    container_name: reservation-api
    image: sandobal-api-reservation:latest
    build:
      context: api.reservation/target/docker/sandobal_reservation_api/
      dockerfile: Dockerfile
    networks:
      - reservationnet
      - servicenet
    ports:
      - 2040:2040
    restart: always
    links:
      - reservation-db
    depends_on:
      - reservation-db
  reservation-db:
    container_name: reservation-data
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 2049:5432
    networks:
      - reservationnet
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=reservation
    volumes:
      - reservation-db:/var/lib/postgresql/data
  # # SANDWICH SERVICE _____________
  sando-ms:
    container_name: sandwich-api
    image: sandobal-api-sandwich:latest
    build:
      context: api.sandwich/target/docker/sandobal_sandwich_api/
      dockerfile: Dockerfile
    networks:
      - sandwichnet
      - servicenet
    ports:
      - 2020:2020
    restart: always
    links:
      - sando-db
    depends_on:
      - sando-db
  sando-db:
    container_name: sandwich-data
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 2029:5432
    networks:
      - sandwichnet
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sandwich
    volumes:
      - sando-db:/var/lib/postgresql/data
  # # INGREDIENT SERVICE _____________
  ingredient-ms:
    container_name: ingredient-api
    image: sandobal-api-ingredient:latest
    build:
      context: api.ingredient/target/docker/sandobal_ingredient_api/
      dockerfile: Dockerfile
    networks:
      - ingredientnet
      - servicenet
    ports:
     - 2030:2030
    restart: always
    links:
      - ingredient-db
    depends_on:
      - ingredient-db
  ingredient-db:
    container_name: ingredient-data
    image: postgres:latest
    restart: unless-stopped
    networks:
      - ingredientnet
    ports:
     - 2039:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ingredient
    volumes:
      - ingredient-db:/var/lib/postgresql/data
volumes:
  sando-db:
  ingredient-db:
  reservation-db:
networks:
  reservationnet: 
  sandwichnet:
  ingredientnet:
  servicenet:
  publicnet: