openapi: 3.0.1
info:
  title: Ingredient
  version: 0.1.0
servers:
- url: "{server}:{port}/ingredient"
  variables:
    server:
      default: http://localhost
    port:
      default: "9091"
paths:
  /list:
    get:
      operationId: getList
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ingredient'
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /:
    get:
      operationId: get
      parameters:
      - name: ingName
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingredient'
        "404":
          description: NotFound
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    Ingredient:
      required:
      - designation
      type: object
      properties:
        designation:
          type: string
