openapi: 3.0.1
info:
  title: Sandwich
  version: 0.1.0
servers:
- url: "{server}:{port}/sandwich"
  variables:
    server:
      default: http://localhost
    port:
      default: "9090"
paths:
  /test:
    get:
      summary: A resource for testing upstream connection
      operationId: getTest
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /list:
    get:
      operationId: getList
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sandwich'
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /:
    get:
      operationId: get
      parameters:
      - name: sandoName
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sandwich'
        "404":
          description: NotFound
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
    post:
      operationId: post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sandwich'
      responses:
        "201":
          description: Created
        "400":
          description: BadRequest
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    Sandwich:
      required:
      - descriptions
      - designation
      - ingredients
      - sellPrice
      type: object
      properties:
        designation:
          type: string
        sellPrice:
          type: number
          format: double
        ingredients:
          type: array
          items:
            $ref: '#/components/schemas/Ingredient'
        descriptions:
          type: array
          items:
            oneOf:
            - $ref: miguel/sando_bal:0.1.0:Language
            - type: string
    Language:
      oneOf:
      - {}
      - {}
      - {}
      - {}
      - {}
    Ingredient:
      required:
      - designation
      type: object
      properties:
        designation:
          type: string
