[container.image]
repository="migueljrpereira" # Docker hub name
name="sando-gateway" # container name
tag="latest"

[settings]
buildImage=false # you can make this false if you don't want to build the image and you just need the Dockerfile
